### ISSUE TITLE
Qr code generation

### ISSUE THREAD

**Issue by rexdivakar** [Monofyi/Bitcope#1]
Create a random string of character length 64 
Store the data into the table with time stamp (Table Name: QuickResponse and columns as Qr_id and Qr_timestamp)
Create a proc to outsource it as an API

**Comment by rexdivakar** [comment]
Generated Qrcode as hash values of length 60 characters with timestamp and status of the code validity 

Currently generated 10000 records for testing.

![image](https://user-images.githubusercontent.com/15235122/101229708-94562f00-36c7-11eb-8cc4-e651e5794ffc.png)

**Comment by Vedsaga** [comment]
> Generated Qrcode as hash values of length 60 characters with timestamp and status of the code validity
> 
> Currently generated 10000 records for testing.
> 
> ![image](https://user-images.githubusercontent.com/15235122/101229708-94562f00-36c7-11eb-8cc4-e651e5794ffc.png)

This is

**Comment by rexdivakar** [comment]
Buddy it's not completely done we need to add functions to trigger it's generation
