### ISSUE TITLE
Same new and old password

### ISSUE THREAD

**Issue by Tawishi** [Monofyi/Bitcope#49]
**Describe the bug**
Password reset to old password allowed.

**To Reproduce**
Steps to reproduce the behaviour:
Try entering the same password in both body parameters.

**Expected behaviour**
Return
{
    "new_password": [
        "Same as old password."
    ]
}

**Comment by rexdivakar** [comment]
Is this issue fixed ? @Tawishi

**Comment by Tawishi** [comment]
Not yet.

**Comment by rexdivakar** [comment]
Hey @Tawishi  this issue is fixed and I'm closing the issue now !
