### ISSUE TITLE
User, owner validation for inserting new worker

### ISSUE THREAD

**Issue by Tawishi** [Monofyi/Bitcope#82]
user and owner ids are may not be correct for a worker row and it still gets inserted in worker table

**Comment by rexdivakar** [comment]
Hey @Tawishi  i just noticed that i wrote the code in such a way that the worker has to be added by the owner and not by the direct insert

**Comment by rexdivakar** [comment]
hey @Tawishi can u please explain more ?

**Comment by Tawishi** [comment]
For instance,
*user_id_id* for owner2 is 2 but we are able to insert a worker with _user_id_id_ = 1 and _owner_id_id_= 2
![image](https://user-images.githubusercontent.com/55306738/111942419-3ffd8080-8af9-11eb-83bb-863b58821692.png)
![image](https://user-images.githubusercontent.com/55306738/111942617-9ec2fa00-8af9-11eb-8dab-23f2481dabd2.png)<br>
that is one can insert a worker with authentication token of user 1, and owner name of owner2 (user2) in postman
![image](https://user-images.githubusercontent.com/55306738/111942713-dfbb0e80-8af9-11eb-9f9b-e0a88772f6a7.png)
<br>
![image](https://user-images.githubusercontent.com/55306738/111942731-e6e21c80-8af9-11eb-9023-7a315b6c3434.png)

**Comment by rexdivakar** [comment]
Right now I'm blocking the owners to create id for the worker so this issue won't happen we can fix it on future models. @Tawishi
